const imgInfos = [ 
    {
        thumnailUrl:"/nutImg/11.jpg",
        moneyUrl:"/qrMoney/1000.png",
        val:1000
    },
    {
        thumnailUrl:"/nutImg/8.jpg",
        moneyUrl:"/qrMoney/300.png",
        val:300
    },
    {
        thumnailUrl:"/nutImg/2.jpg",
        moneyUrl:"/qrMoney/232.png",
        val:232
    },
    {
        thumnailUrl:"/nutImg/3.jpg",
        moneyUrl:"/qrMoney/280.png",
        val:280
    },
    {
        thumnailUrl:"/nutImg/4.jpg",
        moneyUrl:"/qrMoney/299.png",
        val:299
    },
    {
        thumnailUrl:"/nutImg/5.jpg",
        moneyUrl:"/qrMoney/874.png",
        val:874
    },
    {
        thumnailUrl:"/nutImg/6.jpg",
        moneyUrl:"/qrMoney/371.png",
        val:371
    },
    {
        thumnailUrl:"/nutImg/7.jpg",
        moneyUrl:"/qrMoney/350.png",
        val:350
    },
    {
        thumnailUrl:"/nutImg/1.jpg",
        moneyUrl:"/qrMoney/432.png",
        val:432
    },
    {
        thumnailUrl:"/nutImg/9.jpg",
        moneyUrl:"/qrMoney/460.png",
        val:460
    },
    {
        thumnailUrl:"/nutImg/10.jpg",
        moneyUrl:"/qrMoney/550.png",
        val:550
    },
    {
        thumnailUrl:"/nutImg/12.jpg",
        moneyUrl:"/qrMoney/401.png",
        val:401
    },
    {
        thumnailUrl:"/nutImg/13.jpg",
        moneyUrl:"/qrMoney/230.png",
        val:230
    },
    {
        thumnailUrl:"/nutImg/14.jpg",
        moneyUrl:"/qrMoney/555.png",
        val:555
    },
    
]
export default imgInfos